---
title: "**R** per l'analisi statistica multivariata"
description: |
  CdL in Scienze Statistiche ed Economiche, Università Milano-Bicocca 
author:
  - name: Tommaso Rigon
    url: https://tommasorigon.github.io/
    affiliation: DEMS
    affiliation_url: https://dems.unimib.it/it
date: "`r Sys.Date()`"
output: distill::distill_article
---

_R per l'analisi statistica multivariata_ è il primo modulo dell'insegnamento _Analisi Statistica Multivariata_. 

# Ultimi avvisi

* 

# Calendario delle lezioni

| Tipologia | Data | Aula | Orario | Argomenti | 
|-|-|---|----|------|
| Lezione | ?? | ?? | ?? | [Introduzione ad R](slides/sl_A.pdf) |
| Esercitazione | - | - | - | [Introduzione ad R - Esercizi](exe/es_A.html) |



Il materiale didattico di ciascuna lezione è scaricabile utilizzando i [collegamenti ipertestuali](). Si precisa che questa pagina web è soggetta a modifiche, quindi si prega di controllare l'ultima versione aggiornata.

### Calendario delle esercitazioni





#### Testi di riferimento

* 

# Esame


#### Iscrizione all'appello


#### Calendario delle prove parziali di Analisi Esplorativa:


#### Risultati degli appelli




#### Propedeuticità

Questa attività formativa deve essere preceduta dal superamento degli esami di Algebra lineare, Analisi Matematica I, Calcolo delle Probabilità e Statistica I. 

#### Appelli A.A. 2018/19


## Ricevimento {.appendix}

Per fissare un appuntamento, si prega di contattare il docente in anticipo via posta elettronica all'indirizzo . 

## Ringraziamenti {.appendix}

La struttura di questo sito web è largamente ispirata dal sito web dei corsi di Aldo Solari.





