---
title: "R per l'analisi statistica multivariata"
subtitle: "CdL in Scienze Statistiche ed Economiche, Università Milano-Bicocca"
author:
  name: Tommaso Rigon
  affiliation: DEMS
---

L'insegnamento di **Analisi Statistica Multivariata** (15 CFU) è articolato nelle seguenti parti:

1.  R per l'Analisi Statistica Multivariata (R), 3 CFU, II Ciclo, Prof. Rigon.

2.  Modelli Statistici (MS), 6 CFU, III Ciclo, Prof. Ascari.

3.  Analisi Esplorativa (AE), 6 CFU, IV Ciclo, Prof. Monti.

**Nota**: i dettagli legati alle propedeuticità, alla registrazione del voto, al calendario degli esami e al salto d'appello sono spiegate nella pagina Elearning di Analisi Statistica Multivariata.

## Materiale didattico

Il materiale didattico di ciascuna lezione è scaricabile utilizzando i [collegamenti ipertestuali](). Si precisa che questa pagina web è soggetta a modifiche, quindi si prega di controllare l'ultima versione aggiornata.

### Il software R

-   **R** è un software **open source** ed è possibile scaricarlo al link <https://cloud.r-project.org>.

-   L'uso di **Rstudio** è **facoltativo** in questo corso, anche se fortemente consigliato. È possibile scaricarlo al link <https://rstudio.com/products/rstudio/>.

-   La documentazione del software **R** è parte integrante del materiale didattico.

### Testi di riferimento

-   Albert, J. & M. Rizzo (2012). [*R by Example*](https://link.springer.com/content/pdf/10.1007%2F978-1-4614-1365-3.pdf). Springer.\
-   Robert, C. & G. Casella (2010). [*Introducing Monte Carlo Methods with R*](https://link.springer.com/content/pdf/10.1007%2F978-1-4419-1576-4.pdf). Springer

### Testi di consultazione

-   Il materiale didattico aggiuntivo fornito su questa pagina web.
-   Adler, J. (2012). *R in a nutshell*. O'Reilly.
-   Grolemund, G. & Wickham, H. (2016). *R for Data Science*. O'Reilly.
-   Venables, W. N., Smith D. M. & the R Core Team (2021). [*An Introduction to R*](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf).

### Materiale didattico

La sigla **AR** corrisponde al libro di Albert & Rizzo. La sigla **RC** corrisponde al libro Robert & Casella.

| Argomenti                                        | Materiale didattico                        | Materiale aggiuntivo                        | Sezioni libro di testo                                  |
|------------------|------------------|------------------|-------------------|
| Introduzione al corso                            | [Unità introduttiva](lezioni/un_intro.pdf) |                                             |                                                         |
|                                                  | **INTRODUZIONE AD R**                      |                                             |                                                         |
| A-B-C: calcolo scientifico ed algebra lineare    | [Unità A](lezioni/un_A.html)               | [Codice R](lezioni/script/un_A.R)           | **AR** §1.1, §1.3, §A1 --- §A3                          |
| Elementi di programmazione                       | [Unità B](lezioni/un_B.html)               | [Codice R](lezioni/script/un_B.R)           | **AR** §1.2, §1.6 --- §1.8                              |
| I dataframes                                     | [Unità C](lezioni/un_C.html)               | [Codice R](lezioni/script/un_C.R)           | **AR** §1.4 --- §1.5                                    |
| *Esercizi*                                       | [Esercizi 1](exe/es_1.html)                | [soluzione.R](exe/es_1.R)                   |                                                         |
|                                                  | **STATISTICA DESCRITTIVA**                 |                                             |                                                         |
| Analisi descrittiva dei dati `dde`               | [Unità D](lezioni/un_D.html)               | [Codice R](lezioni/script/un_D.R)           | **AR** §2.1 --- §2.3, §2.7                              |
| Analisi descrittiva dei dati `emoglobina`        | [Unità E](lezioni/un_E.html)               | [Codice R](lezioni/script/un_E.R)           | **AR** §2.1 --- §2.3, §2.7                              |
| **Esercitazione**                                | [Unità F](lezioni/un_F.html)               | [Codice R](lezioni/script/un_F.R)           | **AR** 7.1, §7.2                                        |
| Analisi descrittiva dei dati `titanic`           | [Unità G](lezioni/un_G.html)         | [Codice R](lezioni/script/un_G.R)           | **AR** §3.1 --- §3.5                                    |
| *Esercizi*                                       | [Esercizi 2](exe/es_2.html)                | [soluzione.R](exe/es_2.R)                   |                                                         |
|                                                  | **CALCOLO DELLE PROBABILITÀ**              |                                             |                                                         |
| Variabili aleatorie                              | [Unità H](lezioni/un_H.html)         | [Codice R](lezioni/script/un_H.R)           | **RC** §2.1, §2.2                                       |
| Metodi Monte Carlo                               | [Unità I](lezioni/un_I.html)         | [Codice R](lezioni/script/un_I.R)           | **AR** §11.1 --- §11.5, §13.1, §13.2; **RC** §3.1, §3.2 |
| *Esercizi*                                       | [Esercizi 3](exe/es_3.html)                | [soluzione.R](exe/es_3.R)                   |                                                         |
|                                                  | **INFERENZA STATISTICA**                   |                                             |                                                         |
| Metodi numerici per l'analisi di verosimiglianza | [Unità K](lezioni/un_K.html)         | [Codice R](lezioni/script/un_K.R)           | **RC** §5.1, §5.2                                       |
| Proprietà degli stimatori                        | [Unità M](lezioni/un_M.html)         | [Codice R](lezioni/script/un_M.R)           | **AR** §13.3                                            |
| *Esercizi*                                       | [Esercizi 4](exe/es_4.html)                | [soluzione.R](exe/es_4.R)                   |                                                         |
|                                                  | **LEZIONI AGGIUNTIVE**                     |                                             |                                                         |
| Casinò, roulette e metodi Monte Carlo            | [Unità J](lezioni/un_J.pdf)         | [Codice R](lezioni/script/un_J.R)           | **AR** §11.2                                            |
| Minimi quadrati non lineari                      | [Unità L](lezioni/un_L.pdf)         | [Codice R](lezioni/script/un_L.R)           |                                                         |
|                                                  | **ESAMI PASSATI**                          |                                             |                                                         |
| Esame 22 Febbraio 2022                           | [Esame](esami/esame_22_02_2022.html)       | [soluzione.R](esami/soluzione_22_02_2022.R) |                                                         |
| Esame 4 Febbraio 2022                            | [Esame](esami/esame_04_02_2022.html)       | [soluzione.R](esami/soluzione_04_02_2022.R) |                                                         |
| Esame 19 Novembre 2021                           | [Esame](esami/esame_19_11_2021.html)       | [soluzione.R](esami/soluzione_19_11_2021.R) |                                                         |
| Esame 22 Luglio 2021                             | [Esame](esami/esame_22_07_2021.html)       | [soluzione.R](esami/soluzione_22_07_2021.R) |                                                         |
| Esame 30 Giugno 2021                             | [Esame](esami/esame_30_06_2021.html)       | [soluzione.R](esami/soluzione_30_06_2021.R) |                                                         |
| Esame 24 Febbraio 2021                           | [Esame](esami/esame_24_02_2021.html)       | [soluzione.R](esami/soluzione_24_02_2021.R) |                                                         |
| Esame 08 Febbraio 2021                           | [Esame](esami/esame_08_02_2021.html)       | [soluzione.R](esami/soluzione_08_02_2021.R) |                                                         |

### Approfondimenti

#### Articoli scientifici (in inglese)

-   [Hyndman, R. J. and Yanan, F. (1996)](approfondimenti/Hyndman1996.pdf). Sample quantiles in statistical packages. *The American Statistician* **50**(4), 361--365.

-   [Hitchcock (2003)](approfondimenti/Hitchcock2003.pdf). A history of the Metropolis-Hastings algorithm. *The American Statistician* **57**(4), 254--257.

-   [Oldford (2016)](approfondimenti/Oldford2016.pdf). Self-calibrating quantile--quantile plots. *The American Statistician* **70**(1), 74--90.

## Modalità d'esame

L'esame si svolge tramite **computer** e consiste tipicamente in $3$ esercizi da svolgere in **R**. L'esame si svolgerà sulla [Piattaforma Esami Informatizzati](https://esamionline.elearning.unimib.it/login/index.php).

Lo studente all'esame può consultare sia la documentazione ufficiale di **R** che il codice utilizzato a lezione, disponibile a [questo link](lezioni/script.zip).

Per visionare la prova, è possibile venire a ricevimento. Per ulteriori informazioni relative alla registrazione del voto, al calendario delle verbalizzazioni e al salto d'appello si visiti la pagina elearning di Analisi Statistica Multivariata.

## Propedeuticità

Si veda la pagina elearning di Analisi Statistica Multivariata.

## Ricevimento

Per fissare un appuntamento, si prega di contattare il docente in anticipo via posta elettronica all'indirizzo `tommaso.rigon@unimib.it`. Il ricevimento è fissato ogni **martedì alle ore 17.30**.
