---
title: "R per l'analisi statistica multivariata"
subtitle: 'Esiti esame 13 Settembre 2023'
author: "[Tommaso Rigon]{.orange}"
institute: "_Università degli Studi di Milano-Bicocca_"
lang: it
execute:
  cache: false
format:
  html:
    html-math-method: katex
    echo: true
    callout-appearance: minimal
    theme: [cosmo, ../template.css]
    toc: true
    toc-title: Table of contents
    embed-resources: false
    code-line-numbers: false
    smooth-scroll: true
    code-fold: false
    code-summary: "Show the code"
    fig-dpi: 200
    highlight-style: github
editor: 
  markdown: 
    wrap: 72
editor_options: 
  chunk_output_type: console
---

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = F, eval = T, message = F, warning = F, error = F, comment = NA, cache = F, include = T, R.options = list(width = 220))
```

**Nota**. Dalla seguente tabella sono stati omessi gli studenti **Assenti** e **Ritirati**.

```{r}
esiti <- read.csv("ESITI.csv", sep = ";")
esiti <- subset(esiti, select=c(Matricola, Esito))
esiti$Esito[esiti$Esito == "31"] <- "30L"
esiti <- esiti[order(esiti$Matricola),]
esiti <- esiti[esiti$Esito != "ASS" & esiti$Esito != "RIT", ]
knitr::kable(esiti,row.names = FALSE, align = c('l', 'l'))
```
